### ISSUE TITLE
Background of "Works"

### ISSUE THREAD

**Issue by yuisakakibara** [yuisakakibara/2020501#1]
I found that the background color may be better to use white or black color to emphasize the artworks

**Comment by oladhari** [comment]
@yuisakakibara 
please add a checklist about how you are going to proceed.
for example:
- [x] Change the background color to white/black
- [x] update the CSS property
- [x] test the page
- [x] push the PR

**Comment by yuisakakibara** [comment]
@oladhari 

- [背景色を白か黒に変更 ]

- [CSSプロパティを更新 ] 

- [ページを確認 ]  

- [PRを押す ] 
これでやります。

**Comment by yuisakakibara** [comment]
@oladhari 

- [背景を黒に変更したところ、黒色だった文字が読めなくなったのでその文字の色を変更しました
そのため、HTMLの方にも変更したところがあります。 ]
