### ISSUE TITLE
Add Readme file to your folder

### ISSUE THREAD

**Issue by oladhari** [yuisakakibara/2020501#3]
please add a readme file to your project with details of :

- [x] used technologies
- [x] purpose of the project
- [x] link to the hosted web page of this folder

[here](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) a template of Readme file

**Comment by yuisakakibara** [comment]
@oladhari I finished!

**Comment by oladhari** [comment]
after finishing, please check the written checklist in description
